### ISSUE TITLE
[BUG] Heroic Invocation / Greater Heroism immunize Main Character from Weapon Of Awe 

### ISSUE THREAD

**Issue by BananaHamster** [WittleWolfie/CharacterOptionsPlus#151]
**Attach a Bug Report**
https://github.com/WittleWolfie/CharacterOptionsPlus#reporting-problems

**Describe the bug**
As per title.
Casting either of those spells make main character immune to Weapon Of Awe.
No clue why it works on all all other chars, and only main is affected.

**To Reproduce**
1. Cast Greater Heroism or Heroic invocation on Main Character.
2. Cast Weapon Of Awe on Main Character
3. See txt "XYZ is immune to Weapon of Awe"

**Expected behavior**
Not being immune to it :P

**Screenshots**

**Additional context**
If needed, happy to drop a save too.

**Comment by WittleWolfie** [comment]
Very weird. I think this is an Owlcat bug with how they implemented Spell Resistance & Immunity. If I remove the Fear descriptor you can cast it but then the ability won't show the correct descriptors. That's probably fine but maybe misleading since the effect it applies is a Fear effect.

Alternatively I can just make this spell bypass spell resistance on allies, which I suppose is the intended solution.

**Comment by BananaHamster** [comment]
If that works, would be AWEsome - pun intended. :)
What i find the absolute wierdest though is why only main affected. 
If it's the fear causing it - why other chars with fear immunity,
or other buffs that give fear immunity won't stop it from being cast.

I originally suspected it maybe had something to do with main being an angel, but no.
Made Seelah an identical angel - and spell works just fine.
