### ISSUE TITLE
[BUG]Paired Opportunists cannot confirm envir bonus in some cases

### ISSUE THREAD

**Issue by a234106261** [WittleWolfie/CharacterOptionsPlus#162]
**Attach a Bug Report**
[usajcdnl.zip](https://github.com/WittleWolfie/CharacterOptionsPlus/files/14181320/usajcdnl.zip)

**Describe the bug**
Paired Opportunists sometimes cannot offer environment bonus while opportunity attack from Outflank or getting up

**To Reproduce**
1. start a new game and meet seelah, lvl up with feat Outflank and Paired Opportunists
2. Use toybox or other method to make attack critical
3. attack an enemy to trigger opportunity attack, and try to make the enemy fall down then trigger opportunity attack 
5. see error: Paired Opportunists make the attacker gain a attack, but only the main char with feat "one-man Army" get the +4 envir bonus.

**Expected behavior**
Paired Opportunists should gain an extra opportunity attack from another's opportunity attack, and gain +4 envir attack bonus.

**Screenshots**

**Additional context**
The save file is created with only CharacterOptionsPlus and Toybox.
It still offer a extra opportunity attack from a companion opportunity attack.
I had tried to respec the get the feat again but it doesn't change.
Without "a one-man Army" NOBODY gain +4 bonus.

**Comment by WittleWolfie** [comment]
I'll try to take a look this weekend, thanks for the report!

**Comment by a234106261** [comment]
> I'll try to take a look this weekend, thanks for the report!

Any idea about the problem?
I had tried to check the PairedOpportunists.cs code and check my game, and find line 172 not work as expected.
`threatRange: (float)unit.GetThreatRange(attack.WeaponSlot) `
it cannot find any ally engaged, even an ally with threatrange 30 feet.
Once I change it to a readonly number such as 30 feet, this feet works well.

**Comment by adesahark** [comment]
I can't seem to get this perk to activate either.
I had this perk on my Rider and Mount duo, so they should activate when riding.
I can't seem to proc the extra AOO or get the +4 circumstance bonus

I get that the extra AOO might not proc because they usually proc the AOO together anyway, but one instance that only the rider can do AOO is via Tabletop Tweak's Dimensional Retribution, which causes the rider to teleports and make an AOO at the caster.
The Dimensional AOO happens, but I don't see any Circumstance bonus nor the follow-up AOO from the mount
![image](https://github.com/WittleWolfie/CharacterOptionsPlus/assets/28951786/962aa14b-323e-4cf9-8b59-f7c5d6363f95)

I really like the sound of the perk and I hope  I can play with it. Thanks in advance!

**Comment by WittleWolfie** [comment]
Sorry for the slow response, I haven't really been modding wrath / busy with other things.

From your report there's an NPE trying to query threat range. If I can repro should be straightforward to fix.

For the mount issue in the last comment I'm not entirely sure I'll fix but I'll take a look. My suspicion is that the range calculation breaks when mounted.

**Comment by WittleWolfie** [comment]
Fixed this issue.

For the mounted issue I'm not sure and since it's a combination of Mounted + Modded I don't plan to fix, sorry.
